version: "3"
service:
  wordpress:
    image: wordpress:4.9.4-php7-apache
    depends_on:
      - mysql
    container_name: webserver
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=school1
      - WORDPRESS_DB_NAME=webserver
    ports:
      - 3010:80
    networks:
      - web
    volumes:
      - wordpress:/var/www/html

  mysql:
    image: mariadb:10.3.3
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=school1
      - MYSQL_USER=oracle
      - MYSQL_PASSWORD=school1
      - MYSQL_DATABASE=webserver
    networks: 
      - web
    volumes:
      - database:/var/lib/mysql

networks:
  web:
    driver: bridge
volumes:
  wordpress:
  database: